services:
  migration:
    image: ghcr.io/chornonoh-vova/readometer-api:latest
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    command: bun /app/dist/index.js migrate
  api:
    image: ghcr.io/chornonoh-vova/readometer-api:latest
    restart: unless-stopped
    depends_on:
      migration:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=production
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=https://readometer.app
      - TRUSTED_ORIGINS=https://readometer.app
      - DATABASE_URL=${DATABASE_URL}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - STORAGE_PATH=/storage
    volumes:
      - storage_data:/storage
  web:
    image: ghcr.io/chornonoh-vova/readometer-web:latest
    restart: unless-stopped

volumes:
  storage_data:
