services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.39.0
    ulimits:
      memlock: -1
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - database
    ports:
      - "6379:6379"
    environment:
      - DFLY_requirepass=${REDIS_PASSWORD}
      - DFLY_cluster_mode=emulated
      - DFLY_lock_on_hashtags=true
    volumes:
      - dragonfly_data:/data
  postgres:
    image: postgres:18.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d readometer"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=readometer
    volumes:
      - postgres_data:/var/lib/postgresql
  mailpit:
    image: axllent/mailpit:v1.30.6
    networks:
      - database
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MP_DATABASE=/data/mailpit.db
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    volumes:
      - mailpit_data:/data

volumes:
  postgres_data:
  dragonfly_data:
  mailpit_data:

networks:
  proxy:
    name: proxy
  database:
    name: database
