services:
  traefik:
    image: traefik:3.6
    networks:
      - proxy
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.network=proxy"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - proxy
      - database
    environment:
      - BETTER_AUTH_SECRET=cc4jaIIoZviyZ3XmBXcx53FJalipGVS6
      - BETTER_AUTH_URL=http://readometer.local
      - TRUSTED_ORIGINS=http://readometer.local
      - DATABASE_URL=postgres://app:password@postgres:5432/readometer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`readometer.local`) && Path(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`readometer.local`)"
      - "traefik.http.routers.app.entrypoints=web"
  postgres:
    image: postgres:18.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d readometer"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=readometer
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:

networks:
  proxy:
    name: proxy
  database:
    name: database
