services:
  postgres:
    image: postgres:18.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d readometer"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=readometer
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
