/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthAppRouteImport } from './routes/_auth/_app'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/_app.index'
import { Route as AuthAppStatsRouteImport } from './routes/_auth/_app.stats'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRoute = AuthAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppStatsRoute = AuthAppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stats': typeof AuthAppStatsRoute
  '/': typeof AuthAppIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stats': typeof AuthAppStatsRoute
  '/': typeof AuthAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/_app': typeof AuthAppRouteWithChildren
  '/_auth/_app/stats': typeof AuthAppStatsRoute
  '/_auth/_app/': typeof AuthAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/stats' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/stats' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/_app'
    | '/_auth/_app/stats'
    | '/_auth/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_app': {
      id: '/_auth/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAppRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_app/': {
      id: '/_auth/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/_app/stats': {
      id: '/_auth/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthAppStatsRouteImport
      parentRoute: typeof AuthAppRoute
    }
  }
}

interface AuthAppRouteChildren {
  AuthAppStatsRoute: typeof AuthAppStatsRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteChildren: AuthAppRouteChildren = {
  AuthAppStatsRoute: AuthAppStatsRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteWithChildren =
  AuthAppRoute._addFileChildren(AuthAppRouteChildren)

interface AuthRouteRouteChildren {
  AuthAppRoute: typeof AuthAppRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRoute: AuthAppRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
