/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Book {
  author: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: string;
  isbn13: string | null;
  language: string | null;
  publishDate: Timestamp | null;
  title: string;
  totalPages: number;
  updatedAt: Timestamp;
  userId: string;
}

export interface ReadingRun {
  bookId: string;
  completedPages: number;
  deletedAt: Timestamp | null;
  finishedAt: Timestamp | null;
  id: string;
  startedAt: Generated<Timestamp>;
  updatedAt: Timestamp;
  userId: string;
}

export interface ReadingSession {
  deletedAt: Timestamp | null;
  endPage: number | null;
  endTime: Timestamp | null;
  id: string;
  readPages: number;
  runId: string;
  startPage: number | null;
  startTime: Generated<Timestamp>;
  updatedAt: Timestamp;
  userId: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  book: Book;
  readingRun: ReadingRun;
  readingSession: ReadingSession;
  session: Session;
  user: User;
  verification: Verification;
}
